### ISSUE TITLE
issue about Electron with monaco-editor

### ISSUE THREAD

**Issue by PinkyJie** [naumanumer/easybasic#15]
Hey, I'm working on a project which integrates monaco-editor into Electron, I checked your source code and do exactly what you did, but still got errors.

```
<script>var nodeRequire = global.require;</script>
    <script src="../node_modules/monaco-editor/dev/vs/loader.js"></script>
    <script>
      var amdRequire = global.require;
      global.require = nodeRequire;
    </script>
    <script>
      function uriFromPath(_path) {
        var pathName = path.resolve(_path).replace(/\\/g, '/');
        if (pathName.length > 0 && pathName.charAt(0) !== '/') {
          pathName = '/' + pathName;
        }
        return encodeURI('file://' + pathName);
      }
      var path = require('path');
      amdRequire.config({
        baseUrl: uriFromPath(path.join(__dirname, '../node_modules/monaco-editor/dev'))
      });
      var Monaco;
      amdRequire(['vs/editor/editor.main'], function() {
        Monaco = monaco;
      });
    </script>
```

I got an error in this line 
```
r.call(global, RequireFunc, DefineFunc, vmScriptSrc, _this._path.dirname(scriptSrc));
```
in `loader.js`, it seems this line executes the contents of `editor.main.js` (which is the value of `scriptSrc` variable), but got an error. Do you know the reason?

**Comment by naumanumer** [comment]
Its working fine for me now and here is what I am doing:
```html
<!-- Editor style sheets in header -->
<link rel="stylesheet" data-name="vs/editor/editor.main" href="lib/monaco-editor/min/vs/editor/editor.main.css">


<!-- adding the jQuery script at the end -->
    <script type="text/javascript" src="assets/js/jquery.js" onload="window.$ = window.jQuery = module.exports;"></script>

<!-- loading monaco editor -->
    <script>var nodeRequire = global.require</script>
    <script src="lib/monaco-editor/min/vs/loader.js"></script>
    <script>
        var amdRequire = global.require;
        global.require = nodeRequire;
    </script>

<script type="text/javascript" src="assets/js/EditorInitializer.js"></script>
```
In EditorInitializer I just do this:
```javascript
var path = require('path');
amdRequire.config({
    baseUrl: uriFromPath(path.join(__dirname, './lib/monaco-editor/min'))
});
var Monaco; // I want to load monaco async but due to errors i just do this little trick
amdRequire(['vs/editor/editor.main'], function() {
    Monaco = monaco;
})

function InitializeEditor(id, grammer = 'gb'){
    var editor = Monaco.editor.create(document.getElementById(id), {
        language: grammer,
        theme: 'material-dark'
    });
}
```

I call `InitializeEditor` after some time and this will works fine to me.
![image](https://cloud.githubusercontent.com/assets/19629102/19219178/dc25fdf0-8e25-11e6-919b-2ece97e267ad.png)

**Comment by PinkyJie** [comment]
Thanks for your quick response. 
I'm so confused that what I did is exactly the same as you do, but I can't make it. 

<img width="353" alt="2016-10-09 4 46 31" src="https://cloud.githubusercontent.com/assets/551329/19219220/f37a7c5a-8e3f-11e6-8db5-1a866688f0bc.png">

**Comment by naumanumer** [comment]
@PinkyJie I am not an export but just a beginner specially in javascript. so not know what the actual issue is?

**Comment by naumanumer** [comment]
@PinkyJie whats about `nodeIntegration` in my case its `true`

**Comment by naumanumer** [comment]
OR take a look at this branch https://github.com/naumanumer/easybasic/tree/release-0.4 in this version i am loading monaco in an `iframe`

**Comment by PinkyJie** [comment]
@naumanumer The default value of `nodeIntegration` is `true`. `release-0.4` is more beautiful, I'll check that. Thank you!
