### ISSUE TITLE
no editor effect

### ISSUE THREAD

**Issue by carlos121493** [naumanumer/easybasic#16]
hello, i'm confused i got no editor  effect when i installed all dependecies;

![](https://zos.alipayobjects.com/rmsportal/sVsqVVZTpOunlmB.png)

**Comment by naumanumer** [comment]
I dont understand what are you talking abour please explain

**Comment by naumanumer** [comment]
Actually this version is unconstruction and you have to take a look at previous version here https://github.com/naumanumer/easybasic/tree/release-0.4 or you can add editor tab using this in developers console
```javascript
var docitem= {
        title: 'nauman',
        type: 'component',
        componentName: 'Editor',
        componentState: { name: "nauman", id: 'editor1' }
    };
```
```
MainDockerLayout.root.contentItems[ 0 ].contentItems[0].addChild( docitem );
```

**Comment by naumanumer** [comment]
And, the functions `openOrigianl`, `openModified` and `compare` are missing because this code is copied from previous version.

**Comment by naumanumer** [comment]
Added create new button check the commit here https://github.com/naumanumer/easybasic/commit/2de02cd130464b6eeefaac277461b4665965fb1f
